routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/about-us', function () {
    return view('about');
})->name('about');
Route::resource('post','PostController');
Route::resource('userprofile','UserProfileController');
Route::get('donors','MiscController@donors')->name('donors');
Route::get('user/{id}','MiscController@user');
Route::get('post-by-user/{id}','MiscController@postBbyUser')->name('post-by-user');
Route::post('search-post','MiscController@search')->name('search-post');

resources/views/partials/_footer.blade.php
<!-- contact us section -->
<div class="container-fluid">
    <div class="row contactus">
        <div class="col-md-6 offset-md-3">
            <h1 class="text-center">Contact Us</h1>
            <hr class="white-bar">

            <h1 class="text-center">
                <a target="_blank" href="https://www.facebook.com/"><i style="color: #fff;" class="fab fa-facebook-square"></i></a>

                <a target="_blank" href="https://www.youtube.com/"><i style="color: #fff;" class="fab fa-youtube-square"></i></a>
            </h1>

            <div class="details">
                <p><i class="fa fa-phone"> </i> +88 01795 6774893 <br>
                    <i class="fa fa-envelope"> </i> bd2volunteer@gmail.com </p>
            </div>

        </div>
    </div>
</div>
<!-- end contact us section -->

<!-- JQuery File -->
<script type="text/javascript" src="{{url('')}}/custom/jquery/jquery.js"></script>

<!-- BootStrap JS File-->
<script type="text/javascript" src="{{url('')}}/custom/bootstrap/js/bootstrap.min.js"></script>

<!-- Fontawesome Icon JS-->
<script defer src="{{url('')}}/custom/fontawesome/js/all.js"></script>

</body>

</html>

resources/views/partials/_header.blade.php
<!DOCTYPE html>

<head>
    <title>VolunteerBD</title>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Volunteering Website">
    <meta name="author" content="Exceptional Programmers">

    <link rel="stylesheet" href="{{url('')}}/custom/css/styles.css">

    <!-- Bootstrap Link CSS Files -->
    <link rel="stylesheet" type="text/css" href="{{url('')}}/custom/bootstrap/css/bootstrap.min.css">

    <!-- Custom Link CSS Files -->
    <link rel="stylesheet" href="{{url('')}}/custom/css/custom.css">

    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">

</head>

@include('partials._nav')

resources/views/partials/_nav.blade.php
<nav id="mainNav" class="navbar fixed-top navbar-default navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{url('/')}}">VolunteerBD</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">

        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

        </ul>

        <ul class="navbar-nav form-inline my-2 my-lg-0">

            <li class="nav-item">
                <a class="nav-link" href="{{route('home')}}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{route('post.create')}}">Seek Donation</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{route('donors')}}">Donors</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{route('about')}}">About</a>
            </li>
            @guest
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('login') }}">Log in</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('register') }}">Register</a>
                </li>
            @else
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Account
                        <!-- Account -->
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{{route('userprofile.show',Auth::user()->id)}}"><i class="fa fa-user" aria-hidden="true"></i>Profile</a>
                        <a class="dropdown-item" href="{{route('userprofile.edit',Auth::user()->id)}}"><i class="fa fa-edit" aria-hidden="true"></i>Update Profile</a>
                        <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            <i class="fa fa-arrow-circle-left" aria-hidden="true"></i> Logout
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </li>
            @endguest





        </ul>
    </div>
</nav>