routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/about-us', function () {
    return view('about');
})->name('about');
Route::resource('post','PostController');
Route::resource('userprofile','UserProfileController');
Route::get('donors','MiscController@donors')->name('donors');
Route::get('user/{id}','MiscController@user');
Route::get('post-by-user/{id}','MiscController@postBbyUser')->name('post-by-user');
Route::post('search-post','MiscController@search')->name('search-post');

resources/views/donate/create.blade.php
@extends('layouts.custom')

@section('contents')
    <style>
        .size {
            min-height: 0px;
            padding: 60px 0 40px 0;

        }

        .form-container {
            background-color: white;
            border: .5px solid #eee;
            border-radius: 5px;
            padding: 20px 10px 20px 30px;
            -webkit-box-shadow: 0px 2px 5px -2px rgba(89, 89, 89, 0.95);
            -moz-box-shadow: 0px 2px 5px -2px rgba(89, 89, 89, 0.95);
            box-shadow: 0px 2px 5px -2px rgba(89, 89, 89, 0.95);
        }

        .form-group {
            text-align: left;
        }

        h1 {
            color: white;
        }

        h3 {
            color: #e74c3c;
            text-align: center;
        }

        .red-bar {
            width: 25%;
        }
    </style>
    <div class="container size">
        <div class="row">
            <div class="col-md-6 offset-md-3 form-container">
                <h3>Donate Something for Humanity</h3>
                <hr class="red-bar">

                <!-- Error Messages -->
                <form action="{{route('post.store')}}" method="post" enctype="multipart/form-data">
                    @csrf

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type="text" class="form-control" id="title" name="title">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="type">Type</label>
                                <input type="text" class="form-control" id="type" name="type">
                                <p class="help-text">Helps to find in search</p>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="description">Description</label>
                                <textarea name="description" id="description" class="form-control" cols="30" rows="5"></textarea>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="image">Featured Image</label>
                                <input type="file" class="form-control" id="image" name="image">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary" value="Create">
                            </div>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/donate/edit.blade.php
@extends("layouts.custom")

@section("contents")
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Here is your Edit View</h1>
                <a href="{{route('post.index')}}" class="btn btn-success" style="margin-top: 15px;margin-bottom: 15px;">All Post</a>
                <a class="btn btn-danger" title="delete" href="" onclick="if (confirm('Are You Sure To Delete This?')){event.preventDefault();document.getElementById('delete-form{{ $row->id }}').submit();} else {event.preventDefault();}">Delete</a>
                <form id="delete-form{{ $row->id }}" method="post" action="{{ route('post.destroy',$row->id) }}" style="display: none;">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                </form>
            </div>
        </div>
        <form action="{{route('post.update',$row->id)}}" method="post">
        @csrf
        {{method_field("PATCH")}}
        
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control" id="title" name="title" value="{{$row->title}}">
                    </div>
                </div>
            </div>
        
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="type">Type</label>
                        <input type="text" class="form-control" id="type" name="type" value="{{$row->type}}">
                    </div>
                </div>
            </div>
        
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="description">Description</label>
                        <textarea name="description" id="description" class="form-control" cols="30" rows="5">{{$row->description}}</textarea>
                    </div>
                </div>
            </div>
        
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="image">Image</label>
                        <input type="file" class="form-control" id="image" name="image" value="{{$row->image}}">
                    </div>
                </div>
            </div>
        
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary" value="Update">
                    </div>
                </div>
            </div>
        
        </form>
    </div>
@endsection

resources/views/donate/index.blade.php
@extends("layouts.custom")

@section("contents")
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Here is your Index View</h1>
                <a href="{{route('post.index')}}" class="btn btn-success" style="margin-top: 15px;margin-bottom: 15px;">All Bank</a>
            </div>
            <div class="col-md-12">
                <table class="table table-striped">
                     <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Title</th>
                            <th scope="col">Type</th>
                            <th scope="col">Description</th>
                            <th scope="col">Image</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    @php $sl = 1; @endphp
                    @foreach($rows as $row)
                        <tr>
                            <th scope="row">{{$sl++}}</th>
                            <td>{{$row->title}}</td>
                            <td>{{$row->type}}</td>
                            <td>{{$row->description}}</td>
                            <td>{{$row->image}}</td>
                            <td>
                            <a href="{{route('post.show',$row->id)}}" class="btn btn-info">Show</a>
                            <a href="{{route('post.edit',$row->id)}}" class="btn btn-warning">Edit</a>
                            <a class="btn btn-danger" title="delete" href="" onclick="
                                                if (confirm('Are You Sure To Delete This?')){
                                                event.preventDefault();
                                                document.getElementById('delete-form{{ $row->id }}').submit();
                                                }else {
                                                event.preventDefault();
                                                }
                                                ">Delete</a>
                            <form id="delete-form{{ $row->id }}" method="post" action="{{ route('post.destroy',$row->id) }}" style="display: none;">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}
                            </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/donate/show.blade.php
@extends("layouts.custom")

@section("contents")
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Here is your Show View</h1>
                <a href="{{route('post.index')}}" class="btn btn-success" style="margin-top: 15px;margin-bottom: 15px;">All Post</a>
                <a href="{{route('post.edit', $row->id)}}" class="btn btn-warning" style="margin-top: 15px;margin-bottom: 15px;">Edit this Post</a>
                <a class="btn btn-danger" title="delete" href="" onclick="if (confirm('Are You Sure To Delete This?')){event.preventDefault();document.getElementById('delete-form{{ $row->id }}').submit();} else {event.preventDefault();}">Delete</a>
                <form id="delete-form{{ $row->id }}" method="post" action="{{ route('post.destroy',$row->id) }}" style="display: none;">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                </form>
            </div>
        </div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>{{$row->title}}</th>
                </tr>  
    
                <tr>
                    <th>Type</th>
                    <th>{{$row->type}}</th>
                </tr>  
    
                <tr>
                    <th>Description</th>
                    <th>{{$row->description}}</th>
                </tr>  
    
                <tr>
                    <th>Image</th>
                    <th>{{$row->image}}</th>
                </tr>  
    
            </thead>
        </table>
    </div>
@endsection